# Generated by Django 3.2.9 on 2021-12-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartitem_sub_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sub_price',
        ),
    ]
