# Generated by Django 3.1.3 on 2022-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Comfirmed'), ('Delivered', 'Delivered'), ('Refound', 'Refound')], default='Pending', max_length=100),
        ),
    ]
